#!/usr/bin/php
<?php

require __DIR__.'/vendor/autoload.php';

use BristolPhpTraining\cli\Command\SayHelloCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$sayHelloCommand = new SayHelloCommand();
$application->add($sayHelloCommand);
$application->setDefaultCommand($sayHelloCommand->getName(), true);

$application->run();
