#!/usr/bin/php
<?php

require __DIR__.'/vendor/autoload.php';

use BristolPhpTraining\cli\Command\OutputCommand;
use BristolPhpTraining\cli\Command\ProgressCommand;
use BristolPhpTraining\cli\Command\SayHelloCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$sayHelloCommand = new SayHelloCommand();
$application->add($sayHelloCommand);
$application->add(new OutputCommand());
$application->add(new ProgressCommand());


$application->run();
